### ISSUE TITLE
Distro packages

### ISSUE THREAD

**Issue by azizLIGHT** [kozec/sc-controller#1]
Would be nice if we can get some packages to work with, eg: deb for Ubuntu

Thanks for making this

**Comment by kozec** [comment]
They are planned, most likely today. I'm using openSUSE build service that should be able to build DEBs as well, but I yet have to read 20-pages long documentation for debian packaging :'(

**Comment by kozec** [comment]
Just small note - packages are [here](http://software.opensuse.org/download.html?project=home%3Akozec&package=sc-controller) and package for Ubuntu 15.10 is compatible with 16.04.

Actual build for 16.04 crashes on something that I'm assuming is OBS bug (caused by all-beloved systemd -_-), so package for it will be available when that bug is resolved.

**Comment by azizLIGHT** [comment]
Will this work for Ubuntu 14.04?

**Comment by kozec** [comment]
It should. [Try these](https://build.opensuse.org/package/binaries/home:kozec/sc-controller?repository=xUbuntu_14.04)
