### ISSUE TITLE
DPad precision

### ISSUE THREAD

**Issue by Kierek** [kozec/sc-controller#133]
DPad doesn't work as good as with the original Steam Client. 

With the latter I've finished Super Mario World without any problem, it was just as good as with a physical DPad from, let's say, SNES controller. With SC-Controller it's really hard to click the exact buttons I want to, a little shift from the + symbol and I'm pressing both buttons. Could you either rework it so it would work more as a combination of + symbol for directional buttons, X for diagonal and the space inbetween being a deadzone?

Also, since a few versions I'm unable to set any deadzones, probably after commit a70b9483d3efa41d4dfcdf8cdf68bff94e1107e

**Comment by Ryochan7** [comment]
It seems like setting a rotation value of about 15 - 18 degrees is required to get the determined angle in line with the cross on the left touchpad. I would assume that the Steam client has that set by default since there is no rotation setting for DPad output mode.

The DPad action does need a dead zone setting. I just got finished playing Doom 3: BFG using my Steam Controller. I used the DPad action on the analog stick instead of the left touchpad but there were a few times when the stick did not center and the character kept moving. This really is a problem when attempting to survey a gap to prepare for a jump but then end up running off the edge and dying.

**Comment by Kierek** [comment]
I'm really impressed how this little change(rotation) did affect my whole experience, it's exactly as it was on Steam Client, thanks!

**Comment by Ryochan7** [comment]
I made a minor change to allow for a dead zone modifier to be applied for the DPad action type. I ended up changing the behavior of the upper value so that it reflects the maximum possible value as opposed to counting a zero. The distance for the stick coordinates can go slightly over STICK_PAD_MAX when fully pushed in a cardinal direction so pushing fully up on the stick would end up releasing the action bound to a direction.

**Comment by kozec** [comment]
Sorry for late answer, I was pronounced dead for last 3 days :)

DPad currently works [in same way as radial menu with 9 actions](https://cloud.githubusercontent.com/assets/1282500/21516404/24abe3aa-ccd8-11e6-97c7-e16f1d3ec6dd.png), so allowing daead zone is not a problem, but deadzone just "cuts" from entire pad size.

I'll check what or how is Steam doing there.

**Comment by kozec** [comment]
So, after playing with Steam a little, I found it does exactly that - deadzone setting on dpad simply makes large inner part of circle insensitive. That's already being done, so it shouldn't be a problem.

But it is pretty clear that Steam applies input rotation on both pads all the time. I thought values for that are determined by calibration, but it looks like they are hardcoded instead, so now I'm trying to find what they are...

**Comment by Kierek** [comment]
It works great with rotation and inner deadzone, thank you! 

I'm eagerly waiting for any new discoveries.

**Comment by kozec** [comment]
So, to make this working like Steam does _without_ breaking settings for everyone already using SCC, I ended up adding optional global input rotation into controller settings. It will default to same settings as Steam uses for new users (or controllers) and to not rotating anything for anyone who already has some configuration.

To change it, right click on controller icon (left to profile) -> click configure controller and [set it like this.]((https://cloud.githubusercontent.com/assets/1282500/21549964/49ca22a4-cdf6-11e6-9a7c-f3073c5f6ac9.png)
).
