### ISSUE TITLE
Editor window may be too large

### ISSUE THREAD

**Issue by kozec** [kozec/sc-controller#167]
In some cases , with "More" expanded and with all possible options enabled, action editor window doesn't fit fullhd screen.

I'm not really sure how to tackle this without removing options, but it's something that really needs solution, so I'll leave issue here just in case someone has good idea :)

**Comment by Ryochan7** [comment]
Isn't there a scroll area container available in Gtk? At least placing the widgets available once "More" is expanded into a scroll area should be a way around the problem.

**Comment by GlacialTurtle** [comment]
One idea that might be relatively simple for the short term would be Instead of having a singular "More" expansion, to instead have one under each feature toggle hiding the sliders e.g.

```
Smoothing []
> More...

Feedback []
> More...

Enable Deadzone []
> More...
```

This would alleviate the sudden huge expansion from everything being hidden with only 1 "More" item, even if it wouldn't solve the problem permanently (as you still get the same thing when expanding all at once), and would make it easier to solve if/when things get scrolled off screen.

Another idea could be to make the settings into a tabbed interface (if possible) similar to selecting the control type (Joystick/Mouse, DPAD, etc.). Any option that has it's own set of sliders would be moved into it's own tab e.g. Feedback, Deadzone, etc

**Comment by kozec** [comment]
Thanks you both for suggestions.

To put everything into scrolled area sounds like easy way out, but IRRC, scrollbar doesn't play too nice with expanders. So to use tabs sounds better right now, especially if it's possible to align them vertically.

I'll try both :)
