### ISSUE TITLE
Allow Haptic Feedback on More Input Types

### ISSUE THREAD

**Issue by GlacialTurtle** [kozec/sc-controller#179]
Request for some more inputs to be able to have feedback applied to them. The main ones that stand out to me right now are:

D-pad types on pad and analogue stick - feedback should probably trigger in a click-like fashion (similar to the feeling of tapping the edge of the pad when it's set to analogue stick) when touched and bindings are not set to require click. If/when the thumb moves around the pad, clicks should trigger as the boundary is passed to trigger the next binding. This way, if you moved your thumb in a circle, the click would be triggered 8 times on the 4 way dpad (including diagonal overlaps). The above would also apply to the analogue stick when it is set to d-pad.

Soft pull trigger - A click should be allowed to occur when you hit the soft pull point. I don't know if there'd be much point in allowing it for full press.

Mode-shift hold - Click for when you trigger a hold action would be nice.

**Comment by kozec** [comment]
Sorry for answering so late, I somehow overlooked this issue.

All of that should be doable and I'll check how big of change it would be. One problem I can foresee right now is feedback on dpad with Require Click enabled, because with that option, no dpad-related code is executed anywhere until pad is actually pressed.

**Comment by kozec** [comment]
THIS... is now done.
