### ISSUE TITLE
Hip fire trigger style

### ISSUE THREAD

**Issue by KiitoX** [kozec/sc-controller#187]
In Steam the triggers have different trigger styles I especially miss the hip fire exclusive mode which allows me to exclusively trigger the soft binding or the full binding but the other hip fire variants are nice to have as well...

**Comment by kozec** [comment]
(i'm not ignoring this, but I haven't chance to test how hip fire works with steam yet)

**Comment by RiverMatt** [comment]
Any update on this?

**Comment by kozec** [comment]
Saying that I havent run Steam since 2017 is probably not going to fly, right? :)

**Comment by Cybolic** [comment]
I believe it's basically a timing check with three pre-defined timings (my wild guess is `<100`, `<150` and `<200` ms, though these could be replaced by a number input).
Adding it to the check for just the partial press _should_ do the trick so it's just skipped if the user presses to full press within the timing "buffer".

In pseudo-code:
```
partial_press:
    if position < self.release_level and ms_since_press_start >= self.ms_hip_buffer:
        self._press(mapper)
```

**Comment by ren2r** [comment]
I just made a pull request of a basic implementation of hipfire I guess it cover, if not all, most of the hipfire use cases.
Maybe the code is not on par with the rest of application, so @kozec could request some corrections or even rewrite it, but the way it is now is functional and can be used a example of how the hipfire works.

I though of creating a new action instead of a modifier or another aproach just to not breack compatibility with previous profiles, since is a new action it does not interfere with the trigger action or with another modifier.
