### ISSUE TITLE
[Suggestion] Add trigger soft pulls as modeshifts

### ISSUE THREAD

**Issue by Briffo** [kozec/sc-controller#208]
Currently full pulls are the only options for triggers when creating modeshifts (LT/RT). I would greatly appreciate if the soft pulls were added as options as well, if possible. I installed Linux on my hard drive just to see how this software compared with Steam's, and was pleased to learn that it is by far better! Having this one additional feature would make it perfect for me. Thank you for your consideration.

**Comment by kozec** [comment]
Sounds like good idea, I'll check how big problem it would be (trigger works like axis, so code would be completely different from checking state of button)

**Comment by cptMikky** [comment]
I second this one. It is possible in with Steam. 

I've tried to work around it by assigning trigger pull a button and then assigning that button as modeshift but that did not work - the rule did not recurse, i.e. when I soft-pulled the trigger, X button was emulated but no modeshift happened. When I pressed the real X button, modeshift was on. 

So maybe there's the quick'n'dirty way to work around this - allow button recursion and create a "dummy" button and then assign it to soft pull.

**Comment by kozec** [comment]
I'm afraid that allowing that would be more complicated than inventing way to say "left trigger at 75%" in modeshift.

I kinda forgotten about this, but I'll try to add at least non-configurable soft pull, so different modeshift can be used when trigger is pulled and different when trigger "clicks".

**Comment by Patola** [comment]
This is very much needed. The best way to use the gyroscope is to activate it with a half trigger, aim, then press full trigger. By the way, is this the same reason why you can't assign "no action" to the partially pressed action, because it reverts to everything being a "big button"? This annoys me to no end, I would like half-press to output nothing, and have some output when full press is done. I have worked around it by assigning half-press to a key that the game does not recognize. If this is not related to that same difficulty with half-press, please let me know, I will open a separate issue for it.

**Comment by kozec** [comment]
So, this is officially done :)

GUI is little restrictive in comparison of what can be done with custom actions, but it should cover most common use cases.
