### ISSUE TITLE
WINE makes sc-controller throw a LIBUSR_ERROR_BUSY [-6] error

### ISSUE THREAD

**Issue by killstrelok** [kozec/sc-controller#261]
Hi, I've just noticed playing NFS Most wanted [2005] that police chases make sc-controller go crazy, the controls get stuck (ex. constantly turning left and accelerating) and make Xorg freeze (rarely though). Before this happens, my whole PC "hiccups" (freezes) for like a quarter of second and then the error appears.

It wasn't an issue before I reinstalled Xubuntu 16.04 and it occurs with any wine version. Staging, stable, beta - doesn't matter which one I run, I eventually run into that problem. I'm attaching a screenshot of the app, if you need any logs, let me know.

Also, disabling emulation and re-enabling it afterwards fixes the issue for a short time however it's really frustrating.

![screenshot_2017-09-23_13-54-20](https://user-images.githubusercontent.com/25771204/30773435-5de1335a-a068-11e7-9800-98c1ed0910b2.png)

**Comment by kozec** [comment]
Try turning off rumble support and check if it helps. If not, running scc-daemon in console may help to find reason. To do that, disable emulation from GUI and then run `scc-daemon debug` in terminal window.

**Comment by killstrelok** [comment]
Perfect! That solved my issue :) Thank you

**Comment by kozec** [comment]
Np.

**Comment by Kierek** [comment]
I started experiencing this problem since some time, unfortunately I have no idea when exactly. The daemon crashes everytime I start Cemu in Wine and open it's input settings. After some crazy turning off and on the emulation it works stable until the next reboot, but I'm not sure how to reproduce it exactly.

> D SCDongle      Got wireless SC with serial FC61125C24
D SCCDaemon     Assigned default_mapper to <SCWireless FC61125C24>
D SCCDaemon     Controller added: <SCWireless FC61125C24>
D OSD DaemonCtrl    Daemon reported profile change for FC61125C24: None
W SCCDaemon     Refused 'Observe' request: Sniffing disabled
I SCCDaemon     Loaded profile '/home/kierek/.config/scc/profiles/RetroArch.sccprofile'
D OSD DaemonCtrl    Daemon reported profile change for FC61125C24: /home/kierek/.config/scc/profiles/RetroArch.sccprofile
Traceback (most recent call last):
  File "/usr/bin/scc-daemon", line 36, in <module>
    main()
  File "/usr/bin/scc-daemon", line 32, in main
    daemon.debug()
  File "/usr/lib/python2.7/site-packages/scc/sccdaemon.py", line 1049, in debug
    self.run()
  File "/usr/lib/python2.7/site-packages/scc/sccdaemon.py", line 621, in run
    fn()
  File "/usr/lib/python2.7/site-packages/scc/poller.py", line 54, in poll
    self._callbacks.get(fd, DO_NOTHING)(fd, Poller.POLLIN)
  File "/usr/lib/python2.7/site-packages/scc/mapper.py", line 106, in _rumble_ready
    ef = self.gamepad.ff_read()
  File "/usr/lib/python2.7/site-packages/scc/uinput.py", line 348, in ff_read
    id = self._lib.uinput_ff_read(self._fd, MAX_FEEDBACK_EFFECTS, byref(self._ff_events))
TypeError: byref() argument must be a ctypes instance, not 'NoneType'
[kierek@kierekDesktop ~]$ D OSD DaemonCtrl    Connection to daemon lost
E OSD osd.daemon    Connection to daemon lost

**Comment by kozec** [comment]
That stacktrace looks clear enough, I'll try firing up cemu later.

As temporally fix, disabling rumble support should work.

**Comment by Kierek** [comment]
Sorry, I forgot to mention that I already tried disabling rumble emulation and it didn't help.
