### ISSUE TITLE
feedback settings is misleading

### ISSUE THREAD

**Issue by cptMikky** [kozec/sc-controller#294]
Hi,

I spent some time trying to understand feedback settings (for track pad).

I understand what Amplitude is and I *think* I know what frequency means but I'm not sure what period is supposed to do. Also the scale of the settings doesn't make much sense to me.

**Amplitude**: strength of vibration "clicks" - makes sense as it is (maybe except for scale)

**Frequency**: I guess it's absolute axis distance delta for a "click" to happen, i.e how often the "clicks" happen - here the logic of the word is inverted - "frequency" means number of repetitions: the higher the frequency, the more repetitions. In this case the scale is both logically inverted and non-descriptive.

**Period** is, mathematically speaking, the function of "frequency", or, more precisely, inverted value of frequency, therefore it doesn't make logical sense setting them both. In here, "period" probably means minimum (or maximum?) still time between clicks - or at least that's what my short and subjective testing says. However, there is (subjectively) very little difference between minimum and maximum value, So the question is "what is period" and "what does it mean on the scale from 16 to 2^15"?

Since I'm not 100 % sure what "frequency" and "period" means here, I'll refrain from giving suggestions and just humbly ask for explanation :) Suggestions may come after.

-cM.

**Comment by kozec** [comment]
Just wait until I tell you that Period is effectively meaningless :D

To put it simply, Frequency is how often is controller instructed to generate feedback. Period is how often should it repeat that feedback autonomously, once instructed.

Period makes sense only along with additional "count"  parameter, that Steam controller supports, but currently always set to 1. Problem is that once instructed, Controller will generate feedback "count" times no matter what and it can't be interrupted until it's done.

So, Frequency emulates in software, what Period would do in hardware, but it can be controlled better. I agree it's kinda confusing, but I only thing that can be done is hiding Period option entirely, at least until there will be use case where it makes sense.

**Comment by LinuxJoeUser** [comment]
As the guy who hid at the back of the class and copied off the class pothead math-whiz, I'm here to tell y'all using math-based descriptions---however impressive they are to read (and they *are* impressive)---isn't likely to be as meaningful to the average user as more commonplace, layman's descriptions.

Having said that, I'd like to propose that the *amplitude* setting would best be labeled  __"Strength"__ (see ["strength" 1.4 in OED](https://en.oxforddictionaries.com/definition/strength)) as the user's experience is the strength, the forcefulness of the feedback "click".

I'm in agreement with cptMikky about the frequency setting:  sliding the frequency slider to the right should result in more "clicks" in a given time period, not fewer.  "Frequency" is a perfect label for this setting, but the slider must increase the frequency as it moves to the right.  Surely this could be fixed with a little mathematical magic? ;)

**Comment by kozec** [comment]
Reverting sliders and changing labels in UI is no problem and I can clearly how current state can be confusing. It's not for me, but I kinda designed that, so that's probably given :)

But if I go for changing what "frequency=4" saved in _profile file_ means, it will break compatibility with all profiles saved before. And while that can be caught and converted,  I can't see any plus side in doing that.

So, what I'm trying to ask is, are we all talking only about GUI?

**Comment by cptMikky** [comment]
First you should probably ask what "frequency=4" actually means. "Scientifically" speaking it likely means 4 Hz (i.e. 4 repetitions per second) which is probably wrong. 

Then you can either fix just GUI leaving some kind of formula that will transpose whatever the user enters in GUI to the actual scalar (another mathspeak ;) ) parameter "frequency" which would then be saved to the profile, or rework the parameter from scratch, maybe even renaming it to something more sensible. 

I just brainstormed with my GF and we came up with the term "Density" :) It would still require inverted scale to make sense though (the antonym to density being "distribution" which isn't that pretty and is even more confusing than frequency  :) ).

I've noticed there's a "version" parameter in profile definition, that should help with fixing old profiles compatibility should you chose the fix-it-all way.

**Comment by LinuxJoeUser** [comment]
>  ... you can either fix just GUI leaving some kind of formula that will transpose whatever the user enters in GUI to the actual scalar (another mathspeak ;) ) parameter "frequency" which would then be saved to the profile ...

= the mathematical magic I was talking about!  MATH!  Done by MATHEMATICIANS!  PRAISE THEM!

> ... we came up with the term "Density" ...

I'm gonna stick with "Frequency" over "Density" here.  While not entirely inaccurate, if  _Density_ (roughly means [the amount of X in volume Y](https://en.oxforddictionaries.com/definition/density) generally, then _Frequency_ could be understood as a subset of _Density_, i.e. X number of occurrences in Y amount of time.  Frequency is more accurate and more easily understood in this application.

I suppose the label could be the antonym of Frequency:  "Infrequency," which in entirely appropriate and easily understood, but it's also very *weird.*     

Another solution might be to have the Frequency slider  move from right-to-left instead of left-to-right.

**Comment by cptMikky** [comment]
In this sense frequency and density can be considered synonyms as frequency in its vocabulary definition isn't tied only to time-based repetitions.

Even though they effectively mean the same thing, density is better understood as a static occurrence while frequency is likely to be understood as a dynamic variable. 

Technically speaking I believe "density" is more accurate here as the parameter (as I understand it) means how many "feedback triggers" are there on the touch pad. It's not time-based, it behaves as an absolute value. 

However, frequency of feedback vibrations is what user experience is in this case so, well... I guess it depends on the point of view. From technical standpoint, it's density. From UX standpoint it's probably frequency.

**Comment by kozec** [comment]
> Technically speaking I believe "density" is more accurate here as the parameter (as I understand it) means how many "feedback triggers" are there on the touch pad. It's not time-based, it behaves as an absolute value.

Not really, it determines how often will be feedback triggered per traveled distance. So it's not strictly time-based, as it depends on speed of input as well, but it's closer to that than to actual density.



I didn't had much to say, but I've read everything and here is what I'm going to do:
- Period setting will disappear from UI, so people are not confused by how it does exactly nothing
- Frequency slider will be inverted, so right side will mean "many bumps"
- Renaming Frequency to anything is too much effort for no actual effect, so I'll invent some way to use that value as actual frequency to have excuse :)
- I'll add that ^1/256 thing as visual clue, so larger possible frequency with "many bumps" will be 1/4 (0.25Hz) and it will go down to 1/32767 (~0.00003Hz). That way, it shouldn't confuse anyone who understand what Frequency means normally.

**Comment by cptMikky** [comment]
> the parameter ... means how many "feedback triggers" are there on the touch pad. 

and 

>  it determines how often will be feedback triggered per traveled distance

are effectively the same thing. Just saying..

Anyhow, your solution makes good sense also, so thanks for implementing it :)

**Comment by LinuxJoeUser** [comment]
Sounds great Mr. Kozek!  :)

**Comment by kozec** [comment]
Joe, buddy, just one thing. I'm Slavic, not English. There is no way in which writing "Koze**k**" makes any sense with my name :D

Anyway, I ended up shortening those strings, as "1/15 4.56mHZ" takes almost half of window size.

**Comment by Vintodrimmer** [comment]
Just out of curiosity, may I ask you how to pronounce it properly?

**Comment by kozec** [comment]
> Just out of curiosity, may I ask you how to pronounce it properly?

I don't think it can be transcribed to English, but [try this and Click on "listen"](https://translate.google.com/#sk/en/Ko%C5%BEec)
