### ISSUE TITLE
Can't highlight and select lower menu items

### ISSUE THREAD

**Issue by uprightcarrion** [kozec/sc-controller#310]
When using the left pad as a menu the bottom items cannot be selected.   This affects the horizontal list, vertical and the grid.

SCC 4.01
Linux Mint 18.3
Kernel 4.10

**Comment by kozec** [comment]
Can you give me profile or action set on left pad? I can't replicate the problem.

**Comment by uprightcarrion** [comment]
Sorry for the late response.  
[https://drive.google.com/open?id=1aBo_CR6PgkxSqDAJKihmKnwXwYPMdJKW](url)

This is the profile I've been using.  I have the left pad set up as a menu but regardless of the menu type I can't select the bottom item/row.

**Comment by uprightcarrion** [comment]
https://drive.google.com/open?id=1aBo_CR6PgkxSqDAJKihmKnwXwYPMdJKW

**Comment by uprightcarrion** [comment]
![example](https://user-images.githubusercontent.com/7152455/34855301-d24f67e8-f70c-11e7-9eec-4889e5499895.png)


This is the lowest point I can move the cursor.

**Comment by kozec** [comment]
Sorry for late response, I was unable to replicate this no matter what and it took me this long to notice weird thing...

Weird thing here is that your menu looks... compressed? It misses borders and everything seems few pixels shorter than it should. My guess is that this is caused by GTK theme and as results, math is off...

Distro looks like Mint, but what version and what theme are you using? And what version of GTK?

**Comment by uprightcarrion** [comment]
I switched distros to Ubuntu 17.10 and the issue is gone.  If I encounter the issue again I'll reopen the issue and provide more detail.
