### ISSUE TITLE
Appimage Fedora27  

### ISSUE THREAD

**Issue by kodkuce** [kozec/sc-controller#339]
Hi i just installed fresh Fedora 27 and i downloaded sc-controller Appimage but i just get this and when i click ok it closes 

![2018-02-28-18 35 42](https://user-images.githubusercontent.com/24373114/36802940-8856f186-1cb6-11e8-8826-be6103602637.png)

duno if i am missing some dependencies tough i thinked Appimage comes whit them???

**Comment by kozec** [comment]
> duno if i am missing some dependencies tough i thinked Appimage comes whit them???

It leaves Python, GTK and pygi to save space, as that stuff should be installed everywhere. _Should_ is keyword here :)

I should have Fedora in VM around, I'll check what can be done.

**Comment by kozec** [comment]
Ok, it turns out that even with ignoring GTK and Python itself, Fedora needs ~15MB of dependencies _compressed_. I just hope that was my worst-case scenario :(

Can you check if this appimage works for you? [SC_Controller-x86_64.AppImage.zip](https://github.com/kozec/sc-controller/files/1772071/SC_Controller-x86_64.AppImage.zip)

By the way, if you are running Fedora 27, chances are you are under Wayland. Be aware that Wayland doesn't support a some of SCC features, namely OSD and menus.

**Comment by kodkuce** [comment]
Checked now it works yey , ty just now have 1 more issue do i have to install steam first so sc-controller works or not beacuse am getting..   Atm i just wanted to play some NES games and really would like to avoid downloading whole Steam just to enable controller, any workaround ?
![2018-03-01-21 13 57](https://user-images.githubusercontent.com/24373114/36867480-8e2b64e0-1d95-11e8-9044-8c5f8f07db77.png)

**Comment by kodkuce** [comment]
Now it works ty :)

**Comment by kozec** [comment]
Great, thanks for confirmation :)
