### ISSUE TITLE
mouse(Rels.REL_WHEEL, 1) only works once

### ISSUE THREAD

**Issue by DFOXpro** [kozec/sc-controller#361]
# What to do

Set in any button `mouse(Rels.REL_WHEEL, 1)` (mouse wheel scroll Up or scroll Down)
Save and now keep pressing the button key in any scrollable content like a web page

# What to spect

The scrollable content must continuously scroll

# What happen

Only scroll once, event if the button is still pressed

# Who affect

- Gamers of long text reading games
- People who use this driver as an accessibility utility

# Notes

I know this is spected for `mouse()` if no fix needed how should I bind the **mouse** scroll(up/down) and keep scrolling on button hold down

**Comment by kozec** [comment]
That's kinda by design, mostly because scroll wheel really _is_ button, so when you set it like that, you pressing button on gamepad translates to "mouse button 4" being pressed and only releasing gamepad button  releases "mouse button 4". Is up to application to interpret button 4 being held down, but I guess most of them don't expect such possibility.

Anyway, fix is quite simple - wrap that button press into `repeat`. Either with custom action - `repeat(mouse(Rels.REL_WHEEL, 1))` or click on macro and select "Repeat" as type.

**Comment by DFOXpro** [comment]
The problem now looks like the "Key or Button" dnot have the "more" options, there we can choose the repeat option maybe

![imagen](https://user-images.githubusercontent.com/5248241/39667662-f2719c4e-5080-11e8-9f9e-714e74bea466.png)

**Comment by kozec** [comment]
"Macro" button is on top, 2nd from left, not counting "X".

But adding another checkbox where "Toggle button" is, or moving both into "More..." sounds like good idea.
