### ISSUE TITLE
suddenly can't recognize the gamepad

### ISSUE THREAD

**Issue by simbalion** [kozec/sc-controller#396]
Been using sc-controller for weeks without any issues. Today it stopped working. I didn't do any updates. I re-found the controller in Steam using a different USB port and sc-controller still can't see it.

**Comment by kozec** [comment]
Sorry, but this is little too vague to guess anything.

Try disabling emulation and run `scc-daemon debug` from console, it may display some error message that explains what's happening.

**Comment by AlexandreBonneau** [comment]
On my end under Debian Stretch, it stopped too.

When I run `scc-daemon debug`, I see this:
```
scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
W SCCDaemon     Skipping disabled driver 'fake'
D USB           Registered USB driver for 054c:09cc
D USB           Registered USB driver for 28de:1102
D USB           Registered USB driver for 28de:1142
D Mapper        Creating virtual devices
E SCCDaemon     Failed to create uinput device. Error code: -1
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scc/sccdaemon.py", line 442, in init_mapper
    self.scheduler, poller=self.poller)
  File "/usr/lib/python2.7/dist-packages/scc/mapper.py", line 39, in __init__
    self.keyboard = self.create_keyboard(keyboard) if keyboard else Dummy()
  File "/usr/lib/python2.7/dist-packages/scc/mapper.py", line 98, in create_keyboard
    return Keyboard(name=name)
  File "/usr/lib/python2.7/dist-packages/scc/uinput.py", line 538, in __init__
    keyboard=True)
  File "/usr/lib/python2.7/dist-packages/scc/uinput.py", line 268, in __init__
    raise CannotCreateUInputException("Failed to create uinput device. Error code: %s" % (self._fd,))
CannotCreateUInputException: Failed to create uinput device. Error code: -1
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Dummy object at 0x7f015fdef1d0>
D Mapper        Mouse:    <scc.uinput.Dummy object at 0x7f015fdef210>
D Mapper        Gamepad:  <scc.uinput.Dummy object at 0x7f015fdef250>
D SCCDaemon     Created control socket /home/user/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
E USB           Failed to open USB device 28de:1142 : LIBUSB_ERROR_ACCESS [-3]

(scc-osd-daemon.py:5284): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(scc-osd-daemon.py:5284): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(scc-osd-daemon.py:5284): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
D OSD DaemonCtrl    Connected to daemon, version 0.4.3
D OSD DaemonCtrl    Daemon reported error 'Failed to create uinput device. Error code: -1'
D OSD DaemonCtrl    Daemon reported error 'Failed to open USB device: LIBUSB_ERROR_ACCESS [-3]'
```

**Comment by AlexandreBonneau** [comment]
Well, it turns out the `99-input.rules` and `99-steam-controller.rules` files were not part of any Debian package, so I removed those and now it works great.

My bad! ;)

**Comment by kozec** [comment]
Sounds like good explanation. Congrats :)

**Comment by kozec** [comment]
`/etc/udev/rules.d` shouldn't be empty, `90-sc-controller.rules` should be installed there. How did you installed sc-controller?

**Comment by AlexandreBonneau** [comment]
I installed the Debian package from the opensuze.org repository.

I checked and indeed there should have been a file in there since it lists in `dpkg -L sc-controller`.

So I ran `apt install --reinstall sc-controller`, killed `scc-daemon`, closed Steam, unplugged the SC dongle, then replugged it.
Now, I checked and `/dev/uinput` has the `crw-rw----+ 1 root root` permissions.

I checked again and...`/etc/udev/rules.d/` was still empty!?!
No matter how many times I removed/reinstalled the package, the `90-sc-controller.rules` file I can see in the `deb` package was not copied there.

Perhaps this is due to me switching to `testing` a few days ago.

Anyway, I finally copied the file manually, changed its permission to `644 root root`, unplugged and replugged the SC dongle..and `/dev/uinput` permissions still did not change.

I manually ran `chmod 666 /dev/uinput` and then launched sc-controller.
Yet I still have permissions problem `Failed to open USB device 28de:1142 : LIBUSB_ERROR_ACCESS [-3]`, I'm not sure why.

**Comment by kozec** [comment]
You have either reload udev rules (`udevadm control --reload-rules && udevadm trigger`) or reboot, when changing these files manually.

**Comment by AlexandreBonneau** [comment]
Ok so I checked and I do have the file `/etc/udev/rules.d/90-sc-controller.rules` correctly installed by `apt install sc-controller`.
*Before when using `apt install sc-controller` it did not install that file **because** I had manually deleted it, and Debian thought it was part of my own personal configuration. To fix that, I have to `apt remove --purge sc-controller`, then re-install it.*

Anyway, even with this installed, when I reboot `/dev/uinput` permissions are still unchanged with `crw-rw----+ root root` !?!

And like before, even if I manually run `chmod 666 /dev/uinput`, whenever I then run sc-controller, I still get the weird error message `Failed to open USB device 28de:1142 : LIBUSB_ERROR_ACCESS [-3]`.
