### ISSUE TITLE
Switch back to user set "default profile" once an application exits.

### ISSUE THREAD

**Issue by Nilot352** [kozec/sc-controller#446]
As of now sc controller switches to one profile and stays  there and has to be manually switched back but this will allow it to not interfere with other applications if keyboard mapping profiles are set.

**Comment by LinuxJoeUser** [comment]
I'm not sure I would want this behaviour by default  (It's one of the many things I dislike about Steam's SC driver).  Have you thought about creating your own "default" or "desktop" profile and adding it to the "Default" global menu called up when you press the Center button?  Or just adding the desktop to the Autoswitcher under Settings?

**Comment by kozec** [comment]
Bigger problem is that there is no good way to tell when application exits, unless it's started by SCC itself. And even that would be buggy, because there are programs that will exit immediately and start new process in background (like Atom or Technic Launcher).

So unless someone has some clever idea how to actually do it, I don't think it's possible.
