### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Dnlaua** [kozec/sc-controller#475]
I love sc-controller but my dolphin emulator on Manjaro isn't loading the save states from a previous version which I was using on Ubuntu. I will still use this on Ubuntu, but how do I uninstall sc-controller from Manjaro as I can't use the dolphin emulator on there with my old save states?

I didn't think either of these commands would work since it's installed using python, but I tried `pacman`and `pamac` with no luck.

Also tried `pip uninstall sc-controller` but it says `WARNING: Skipping sc-controller as it is not installed.` Tried `pip freeze` and I don't see anything that is related to sc-controller.

**Comment by kozec** [comment]
How did you installed it in 1st place? :)

**Comment by Dnlaua** [comment]
I tried `sudo pacman -R sc-controller` but it says target not found. I installed using the setup.py, so I tried `pip uninstall sc-controller` but it says `WARNING: Skipping sc-controller as it is not installed.` When I run `sc-controller` through terminal it still opens though.

**Comment by kozec** [comment]
Maybe you used **sudo** setup.py? 

Anyway, since you haven't used package manager, it may be faster to just manually remove files. Make sure you have up-to-date backup and remove:
- `/usr/share/scc`
- `/usr/lib/python2.7/site-packages/scc`
- `/share/pixmaps/sc-controller.svg`
- `/usr/share/mime/packages/scc-mime-types.xml`
- `/usr/share/applications/sc-controller.desktop`
- `/usr/lib/udev/rules.d/69-sc-controller.rules`
- all `scc-XYZ` icons from `/usr/share/icons/hicolor/24x24/status` and `/usr/share/icons/hicolor/256x256/status`.
