### ISSUE TITLE
Daemon reported error 'CANT_SUMMON_THE_DAEMON'

### ISSUE THREAD

**Issue by legluondunet** [kozec/sc-controller#489]
Hello,
I have a bug for several weeks now, still present in today's git 12 august 2019.
Sometimes, when I launch sc-controller, I obtain an erro r about sc DAEMON :

```
/run.sh --debug
D App           daemon status: unknown
D App           daemon status: unknown
pidfile /home/romain/.config/scc/daemon.pid does not exist. Daemon not running?
D DaemonCtrl    Started daemon but connection is not ready
D App           Daemon reported error 'CANT_SUMMON_THE_DAEMON'
D App           daemon status: error
```
When this happened, all I can do is restart the computer.

Config: Ubuntu 19.04

**Comment by kozec** [comment]
Try starting `./daemon.sh debug` (or `scc-daemon debug`) in another terminal and check whether it displays any error message when it happens.

**Comment by legluondunet** [comment]
as asked:

```
$ ./daemon.sh start debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
W SCCDaemon     Skipping disabled driver 'fake'
D USB           Registered USB driver for 054c:09cc
I remotepad     Listening on 0.0.0.0:55400
D USB           Registered USB driver for 28de:1102
D USB           Registered USB driver for 28de:1142
D Mapper        Creating virtual devices
Exception AttributeError: "'Keyboard' object has no attribute '_fd'" in <bound method Keyboard.__del__ of <scc.uinput.Keyboard object at 0x7f22eba87e90>> ignored
```

**Comment by kozec** [comment]
Okay, this is kinda known bug, it happens when uinput kernel module gets locked. That can be caused by application communicating with it in wrong way and I was not able to find what exactly in SCC can cause this. On that note, try disabling rumble emulation (in sc-controller settings) check if it stops happening.

What's interesting here is that it sounds like you've started daemon first thing after boot. That would indicate _some other_ program worked with uinput and left it in locked state. Are you using anything else related to gamepad or keyboard emulation?

**Comment by legluondunet** [comment]
Before launching scc, I effectively used antimicro.
