### ISSUE TITLE
Windows 10 Entry Point Not Found

### ISSUE THREAD

**Issue by greatwroth** [kozec/sc-controller#521]
sc-controller-0.4.9.9-win32-pre-release on Windows 10 Pro I get this pop-up when I try to run sc-controller.exe

![csrss_2019-12-12_13-29-46](https://user-images.githubusercontent.com/3023924/70750698-b8b14280-1ce3-11ea-9edc-9e26b7f340a0.png)

when I click OK the process closes

Running the daemon directly seems to work fine though.

**Comment by kozec** [comment]
So, I was unable to reproduce this in any way _and_ I have no idea how could it happen, so I can only ask if it still happens with pre-release I've just added.

**Comment by greatwroth** [comment]
Unfortunately it does still happen with the new version. If you're curious I would gladly run a debug/logging version if you think it could be useful. Otherwise still perfectly usable running daemon directly.

**Comment by kozec** [comment]
There is `sc-controller-console.exe` in v 4.9.10 that may display more error messages, but this seems pretty clear. It just doesn't make any sense.

Do you have any other version of `libpng-16.dll` lying somewhere in c:/windows or some subdirectory? Maybe it's loaded instead of one in sc-controller directory.

**Comment by greatwroth** [comment]
There was a zlib1.dll in C:\Windows\SysWOW64, recycled and now sc-controller.exe works. Thank you.
