### ISSUE TITLE
Error reported by sc-controller: Failed to create uinput device. Error code: -1

### ISSUE THREAD

**Issue by rah2501** [kozec/sc-controller#607]
Hi,

I've installed the 0.4.8 Debian packages from OBS as described [here](https://software.opensuse.org/download.html?project=home%3Akozec&package=sc-controller).  I've set appropriate permissions on /dev/uinput:

```
rah@lotus:~$ ls -l /dev/uinput
crw-rw---- 1 root input 10, 223 Dec 15 00:12 /dev/uinput
rah@lotus:~$ groups | grep -qw input && echo input present
input present
```

Unfortunately, when I run sc-controller, I'm told "Failed to create uinput device. Error code: -1":

![sc-controller-failed-to-create-uinput-device](https://user-images.githubusercontent.com/4304655/102151796-8cd31a80-3e6b-11eb-865b-b6776a266f09.png)

The terminal output reports:

```
rah@lotus:~$ sc-controller
W App           Failed to read release notes
E App           g-io-error-quark: The specified location is not supported (15)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scc/gui/app.py", line 1516, in http_ready
    stream = f.read_finish(task)
Error: g-io-error-quark: The specified location is not supported (15)
W App           (above error is not fatal and can be ignored)
```

There is no /dev/input/js* file created.

**Comment by kozec** [comment]
Try calling `modprobe uinput` just in case and then turn off everything scc-related and run `scc-daemon debug`, it should display error more messages.

**Comment by PeterNerlich** [comment]
*Merry Christmas!*

On Arch, stuff like this happens to me from time to time after updating the kernel package whose kernel is currently in use when I not immediately reboot and of course forget about it. The system runs just fine as the kernel and important modules are in memory, but if a new unloaded module is required, it is not found, as the kernel and it's modules are not on the hard drive anymore, in their place only the newer kernel version and modules. As their containing directory is named incorporating the version, the currently running kernel cannot accidentally grab the wrong modules and instead just fails to load them:

    $ modprobe uinput
    modprobe: FATAL: Module uinput not found in directory /lib/modules/5.4.82-1-lts
    $ ls /lib/modules
    5.4.85-1-lts  5.9.14-arch1-1

In this case, rebooting helps, since the new kernel will be used.

Not sure whether Debian handles this much differently and whether this is actually what you're experiencing.

**Comment by rah2501** [comment]
> turn off everything scc-related and run `scc-daemon debug`, it should display error more messages.

I tried this but in the meantime I'd rebooted my machine and now sc-controller seems to work without any problems.  Closing the issue for now, if the problem happens again I'll reopen.

**Comment by rah2501** [comment]
> Not sure whether Debian handles this much differently and whether this is actually what you're experiencing.

Debian handles this very differently.
